version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    labels:
      - "security"
      - "dependencies"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    groups:
      security-updates:
        patterns:
          - "*"
